theme = "blowfish"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 0
buildDrafts = false
buildFuture = false
enableEmoji = true
baseURL = "https://phelewski.github.io/recipe-blog/"

[pagination]
pagerSize = 100

[imaging]
anchor = "Center"

[taxonomies]
tags = "tags"
categories = "categories"
cuisine = "cuisine"
method = "method"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]

[related]
threshold = 0
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 40

[[related.indices]]
name = "cuisine"
weight = 30

[[related.indices]]
name = "method"
weight = 20

[[related.indices]]
name = "date"
weight = 10

[[related.indices]]
applyFilter = false
name = "fragmentrefs"
type = "fragments"
weight = 10
